name: Build dataset

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        name: Store version
        run: echo "version=v$(date +%Y%m%d)" >> $GITHUB_OUTPUT
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install gbizinfo-lod
        run: pip install gbizinfo-lod
      - name: Download CSV files
        run: gbilod download --sleep 1 . && rm Kihonjoho_UTF-8.csv
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.version.outputs.version }}
          path: "*.csv"

  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: download
    steps:
      - run: df -hT
      - run: lscpu
      - name: Install pigz
        run: sudo apt-get update && sudo apt-get install -y pigz && apt-get clean && rm -rf /var/lib/apt/lists/*
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install gbizinfo-lod
        run: pip install gbizinfo-lod
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.download.outputs.version }}
      - name: Convert CSV files to RDF
        run: mkdir -p rdf && gbilod convert -f nq -p 2 -c -o rdf .
      - name: Count triples
        run: |
          for F in *.nq.gz; do echo "- $F: $(printf "%'d" $(pigz -dc -f < "$F" | wc -l)) quads" >> summary.txt ; done
        working-directory: ./rdf
      - name: Split large files
        run: |
          pigz -dc hojin.nq.gz | split -b 20G -a 1 -d --verbose --filter="pigz -9 > \$FILE.nq.gz" - "hojin.part" \
          && hojin.nq.gz \
          && pigz -dc tokkyo.nq.gz | split -b 20G -a 1 -d --verbose --filter="pigz -9 > \$FILE.nq.gz" - "tokkyo.part" \
          && tokkyo.nq.gz \
        working-directory: ./rdf
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: $version
          files: ./rdf/*.nq.gz
          body_path: ./rdf/summary.txt
